/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExportInquiry {
  'estimatedQuantity' : string,
  'contactPerson' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
  'companyName' : string,
  'phone' : string,
  'destinationCountry' : string,
  'englishTranslation' : [] | [string],
  'productsOfInterest' : Array<string>,
  'inquiryId' : bigint,
}
export interface Order {
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : Time,
  'orderId' : bigint,
  'shippingAddress' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
  'contactDetails' : string,
}
export interface OrderItem {
  'name' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'unitPrice' : [] | [bigint],
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'processed' : null };
export interface Product {
  'processPicture' : [] | [string],
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'price' : [] | [bigint],
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInitialCatalog' : ActorMethod<[], undefined>,
  'getAllExportInquiries' : ActorMethod<[], Array<ExportInquiry>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAvailableProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExportInquiryById' : ActorMethod<[bigint], ExportInquiry>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'getProductCategories' : ActorMethod<[], Array<string>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitExportInquiry' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      [] | [string],
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];